### ISSUE TITLE
Can't train to convergence

### ISSUE THREAD

**Issue by wuyaozong99** [orobix/fwdgrad#10]
Hi, thanks for your implementation!

When i run the mnist_fwdgrad.py and choose the Conv model, the train loss doesn‘t decrease as in the paper, but decreases to 1.7 and then suddenly rises to more than 14. The training is divergent, unable to train to convergence. Have you ever encountered this problem?

**Comment by belerico** [comment]
Hi @wuyaozong99, sorry for the late response. Have you run the training with the default hyperparams? Have you tried also with the MLP network?

**Comment by wuyaozong99** [comment]
@belerico Thanks for your reply. I found that I used a fixed learning rate 2e-4 instead of the default setting, which decreased with iteration. After using the default settings, the divergence phenomenon is alleviated.

**Comment by wuyaozong99** [comment]
Now another problem is bothering me.
When using a model with normalization layers, such as BatchNormalization, I must chahge `fmodel, params = fc.make_functional(model)` to ` fmodel, params, buffers = fc.make_functional_with_buffers(model)`
Then i change the `functional_xent`, add a param buffers to pass the buffers. Now the `functional_xent` is like this
`def functional_xent(params, model, x, t, num_classes,buffers) -> torch.Tensor:`
`    y = model(params,buffers, x)`
`    return _xent(y, t, num_classes)`
And then,
`f = partial(`
`             functional_xent,`
`             model=fmodel,`
`             buffers = buffers,`
`             x=images.to(DEVICE),`
`             t=labels.to(DEVICE),)`
Then i run the mnist_fwdgrad.py, an error was reported when calculating the jvp:
`RuntimeError: During a grad (vjp, jvp, grad, etc) transform, the function provided attempted to call in-place operation (aten::add_.Tensor) that would mutate a captured Tensor. This is not supported; please rewrite the function being transformed to explicitly accept the mutated Tensor(s) as inputs.`       
It's a little difficult to solve with my poor knowledge, do you have any method? I think that by solving this problem, we can extend forward gradient to more models which have the normalization layers.
